# Generated by Django 4.1.13 on 2024-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_timestamp_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='slugSome', max_length=600),
            preserve_default=False,
        ),
    ]
