# Generated by Django 4.1.13 on 2024-01-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_comment_id_comment_isreply_alter_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='isReply',
        ),
    ]
