# Generated by Django 4.1.13 on 2024-01-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_tutorial_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
