# Generated by Django 4.1.13 on 2024-01-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_tutorial_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='course_id',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='course',
            field=models.CharField(default='Course A', max_length=500),
            preserve_default=False,
        ),
    ]
