# Generated by Django 4.1.13 on 2024-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_tutorial_course_id_tutorial_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.CharField(default='slugSome', max_length=600),
            preserve_default=False,
        ),
    ]
