# Generated by Django 4.1.13 on 2024-01-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tutorial_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
